/**
 * challenges.js — bash editing challenges organised into a structured learning track.
 *
 * Each challenge:
 *   id           — unique number
 *   collectionId — which collection this belongs to
 *   title        — short name shown in the UI
 *   description  — one-sentence explanation
 *   initial      — the command the player starts with
 *   target       — the command the player must produce
 *   hint         — which shortcut(s) to use
 *   optimalKeys  — keystrokes needed with the optimal shortcut approach
 *   category     — shortcut family (same as collectionId for consistency)
 *
 * Ctrl+W note:
 *   In Electron (the primary build) Ctrl+W works fully — hints use it.
 *   In a browser Ctrl+W closes the tab; use Alt+Backspace there instead.
 */

// ── Collection 1: Line Navigation ─────────────────────────────────────────────
const lineNavChallenges = [
  { id:15, collectionId:'line-nav', title:'Add sudo at the front', description:"Prepend 'sudo ' to the apt command.", initial:'apt install -y build-essential', target:'sudo apt install -y build-essential', hint:'Ctrl+A jumps to start of line; type "sudo " (6 chars).', optimalKeys:6, category:'line-nav' },
  { id:16, collectionId:'line-nav', title:'Append a redirect', description:"Add ' > output.txt' at the end.", initial:'grep -rn TODO /home/user/projects', target:'grep -rn TODO /home/user/projects > output.txt', hint:'Ctrl+E jumps to end of line; type " > output.txt".', optimalKeys:13, category:'line-nav' },
  { id:27, collectionId:'line-nav', title:'Add verbose output', description:"Add '-v' flag right after 'make'.", initial:'make install PREFIX=/usr/local', target:'make -v install PREFIX=/usr/local', hint:'Ctrl+A then Alt+F moves past "make"; type " -v" to insert the flag.', optimalKeys:5, category:'line-nav' },
  { id:101, collectionId:'line-nav', title:'Add nohup', description:"Prepend 'nohup ' so the process survives logout.", initial:'python3 -m http.server 8080 &', target:'nohup python3 -m http.server 8080 &', hint:'Ctrl+A to jump to start, then type "nohup " (6 chars).', optimalKeys:7, category:'line-nav' },
  { id:102, collectionId:'line-nav', title:'Capture stderr', description:"Add ' 2>&1' at the end to redirect stderr to stdout.", initial:'make build', target:'make build 2>&1', hint:'Ctrl+E jumps to end of line; type " 2>&1".', optimalKeys:6, category:'line-nav' },
  { id:201, collectionId:'line-nav', title:'Add a background job', description:"Append ' &' to run the command in the background.", initial:'npm run dev', target:'npm run dev &', hint:'Ctrl+E jumps to end; type " &".', optimalKeys:3, category:'line-nav' },
  { id:202, collectionId:'line-nav', title:'Prepend time', description:"Prepend 'time ' to measure how long the command takes.", initial:'cargo build --release', target:'time cargo build --release', hint:'Ctrl+A to go to start, then type "time ".', optimalKeys:6, category:'line-nav' },
  { id:203, collectionId:'line-nav', title:'Redirect to devnull', description:"Add ' > /dev/null 2>&1' at the end.", initial:'find / -name lost+found', target:'find / -name lost+found > /dev/null 2>&1', hint:'Ctrl+E jumps to end; type " > /dev/null 2>&1".', optimalKeys:19, category:'line-nav' },
  { id:204, collectionId:'line-nav', title:'Prepend env var', description:"Prepend 'RUST_LOG=debug ' to the cargo run command.", initial:'cargo run --bin server', target:'RUST_LOG=debug cargo run --bin server', hint:'Ctrl+A, then type "RUST_LOG=debug ".', optimalKeys:14, category:'line-nav' },
];

// ── Collection 2: Word Navigation ─────────────────────────────────────────────
const wordNavChallenges = [
  { id:12, collectionId:'word-nav', title:'Add a flag in the middle', description:"Add '-a' to make 'ls -l' into 'ls -la'.", initial:'ls -l /home/user/documents', target:'ls -la /home/user/documents', hint:'Ctrl+A then Alt+F x2 puts the cursor right after "-l"; type "a".', optimalKeys:4, category:'word-nav' },
  { id:13, collectionId:'word-nav', title:'Upgrade the image tag', description:"Change 'ubuntu:20.04' to 'ubuntu:22.04'.", initial:'docker pull ubuntu:20.04', target:'docker pull ubuntu:22.04', hint:'Alt+B jumps back one word; land on "20", delete and retype.', optimalKeys:5, category:'word-nav' },
  { id:18, collectionId:'word-nav', title:'Fix the filename extension', description:"Change 'config.yml' to 'config.yaml'.", initial:'ansible-playbook -i hosts config.yml --check', target:'ansible-playbook -i hosts config.yaml --check', hint:'Alt+B x2 from end navigates to the extension; insert "a".', optimalKeys:5, category:'word-nav' },
  { id:19, collectionId:'word-nav', title:'Correct the Python version', description:"Change 'python2' to 'python3'.", initial:'python2 manage.py runserver 0.0.0.0:8000', target:'python3 manage.py runserver 0.0.0.0:8000', hint:'Ctrl+A, Alt+F jumps to end of "python2"; Backspace, type "3".', optimalKeys:4, category:'word-nav' },
  { id:103, collectionId:'word-nav', title:'Change the environment', description:"Change 'staging' to 'production' in the namespace flag.", initial:'helm upgrade --namespace staging my-app ./chart', target:'helm upgrade --namespace production my-app ./chart', hint:'Alt+B x3 from end (or Ctrl+A + Alt+F x3) lands on "staging"; replace it.', optimalKeys:14, category:'word-nav' },
  { id:205, collectionId:'word-nav', title:'Bump the node version', description:"Change 'node:18' to 'node:22' in the docker run command.", initial:'docker run --rm node:18 node --version', target:'docker run --rm node:22 node --version', hint:'Alt+B x3 from end to reach "18"; delete and type "22".', optimalKeys:5, category:'word-nav' },
  { id:206, collectionId:'word-nav', title:'Change the AWS region', description:"Change 'us-east-1' to 'eu-west-1'.", initial:'aws s3 ls --region us-east-1 s3://my-bucket', target:'aws s3 ls --region eu-west-1 s3://my-bucket', hint:'Alt+B x2 from end lands on "us"; delete and type "eu".', optimalKeys:8, category:'word-nav' },
  { id:207, collectionId:'word-nav', title:'Switch the git protocol', description:"Change 'https' to 'ssh' in the remote add command.", initial:'git remote add origin https://github.com/user/repo.git', target:'git remote add origin ssh://github.com/user/repo.git', hint:'Alt+B x2 from end lands on "https"; delete 5 chars and type "ssh".', optimalKeys:8, category:'word-nav' },
  { id:208, collectionId:'word-nav', title:'Fix the test pattern', description:"Change 'unit' to 'integration' in the jest command.", initial:'jest --testPathPattern=unit --coverage', target:'jest --testPathPattern=integration --coverage', hint:'Alt+B x2 lands on "unit"; delete 4 chars and type "integration".', optimalKeys:15, category:'word-nav' },
];

// ── Collection 3: Character Navigation ────────────────────────────────────────
const charNavChallenges = [
  { id:25,  collectionId:'char-nav', title:'Quieter curl',              description:"Add the -s (silent) flag to curl.",                          initial:'curl -o report.html https://example.com/report',          target:'curl -so report.html https://example.com/report',          hint:'Ctrl+A, Alt+F, Ctrl+F x2 puts cursor right after "-"; type "s".',          optimalKeys:5, category:'char-nav' },
  { id:104, collectionId:'char-nav', title:'Switch compression',        description:"Change the 'z' (gzip) flag to 'j' (bzip2) in tar.",         initial:'tar -xzvf archive.tar.gz',                                target:'tar -xjvf archive.tar.gz',                                hint:'Ctrl+A, then Ctrl+F x5 lands on "z"; Ctrl+D deletes it, type "j".',        optimalKeys:7, category:'char-nav' },
  { id:105, collectionId:'char-nav', title:'Fix an off-by-one uid',     description:"Change uid 1001 to 1000 in the useradd command.",           initial:'useradd -u 1001 -g 1000 appuser',                         target:'useradd -u 1000 -g 1000 appuser',                         hint:'Navigate to the last digit of "1001"; Backspace + type "0".',              optimalKeys:5, category:'char-nav' },
  { id:106, collectionId:'char-nav', title:'Toggle the flag letter',    description:"Change '-n' to '-m' in the head command.",                  initial:'head -n 20 /var/log/syslog',                              target:'head -m 20 /var/log/syslog',                              hint:'Ctrl+A + Ctrl+F x6 puts cursor on "n"; Ctrl+D, then type "m".',           optimalKeys:8, category:'char-nav' },
  { id:209, collectionId:'char-nav', title:'Fix a file permission digit',description:"Change chmod 644 to 755.",                                 initial:'chmod 644 /usr/local/bin/myapp',                          target:'chmod 755 /usr/local/bin/myapp',                          hint:'Ctrl+A + Ctrl+F x6 lands on "6"; Ctrl+D type "7"; Ctrl+F Ctrl+D type "5".', optimalKeys:9, category:'char-nav' },
  { id:210, collectionId:'char-nav', title:'Increment the retry count', description:"Change '--retry 3' to '--retry 5'.",                        initial:'curl --retry 3 --retry-delay 2 https://api.example.com', target:'curl --retry 5 --retry-delay 2 https://api.example.com', hint:'Navigate to "3" after "--retry"; Backspace + type "5".',                   optimalKeys:6, category:'char-nav' },
  { id:211, collectionId:'char-nav', title:'Fix a typo mid-option',     description:"Fix '--sinc' to '--sync' in the rsync command.",            initial:'rsync -av --sinc /src/ /dst/',                            target:'rsync -av --sync /src/ /dst/',                            hint:'Navigate to "i" in "--sinc"; Ctrl+D + type "y".',                         optimalKeys:7, category:'char-nav' },
];

// ── Collection 4: Character Deletion ──────────────────────────────────────────
const charDelChallenges = [
  { id:8,   collectionId:'char-del', title:'Remove a repeated flag',    description:'Remove the extra "v" flag in the tar command.',            initial:'tar -xzvvf archive.tar.gz -C /tmp',                       target:'tar -xzvf archive.tar.gz -C /tmp',                        hint:'Navigate just before the extra "v"; Ctrl+D deletes the character at the cursor.', optimalKeys:5, category:'char-del' },
  { id:17,  collectionId:'char-del', title:'Fix the command name',      description:"Fix typo 'grpe' to 'grep'.",                               initial:"grpe -r 'function main' /src",                            target:"grep -r 'function main' /src",                            hint:'Ctrl+A, Ctrl+F x2 lands between "gr" and "pe"; Ctrl+D x2 + type "ep".',   optimalKeys:6, category:'char-del' },
  { id:23,  collectionId:'char-del', title:'Extend the find depth',     description:"Change '-maxdepth 2' to '-maxdepth 4'.",                   initial:'find /etc -maxdepth 2 -name "*.conf" -type f',            target:'find /etc -maxdepth 4 -name "*.conf" -type f',            hint:'Navigate to "2" after "-maxdepth"; Backspace, type "4".',                  optimalKeys:5, category:'char-del' },
  { id:107, collectionId:'char-del', title:'Remove duplicate slash',    description:"Fix the double slash '//etc' in the path.",                initial:'cat //etc/hosts',                                         target:'cat /etc/hosts',                                          hint:'Ctrl+A, Ctrl+F x5 puts cursor on the second "/"; Ctrl+D removes it.',      optimalKeys:6, category:'char-del' },
  { id:212, collectionId:'char-del', title:'Delete a stray character',  description:"Fix 'ls -la.' to 'ls -la'.",                               initial:'ls -la.',                                                 target:'ls -la',                                                  hint:'Cursor is already at end; Backspace removes the trailing ".".',            optimalKeys:1, category:'char-del' },
  { id:213, collectionId:'char-del', title:'Fix a doubled letter',      description:"Fix 'sttrace' to 'strace' in the debug command.",          initial:'sttrace -p 1234 -e trace=network',                        target:'strace -p 1234 -e trace=network',                         hint:'Ctrl+A, Ctrl+F x2 lands on the second "t"; Ctrl+D removes it.',           optimalKeys:3, category:'char-del' },
  { id:214, collectionId:'char-del', title:'Remove an extra dash',      description:"Fix '--force-push' to '--force' by removing '-push'.",     initial:'git push --force-push origin main',                       target:'git push --force origin main',                            hint:'Navigate to "-" in "-push"; Ctrl+D x5 removes "-push".',                   optimalKeys:9, category:'char-del' },
];

// ── Collection 5: Cut to End (Ctrl+K) ─────────────────────────────────────────
const killEndChallenges = [
  { id:1,   collectionId:'kill-end', title:'Cut the tail',              description:'Remove everything from --delete onwards.',                  initial:"find /var/log -name '*.log' -type f -mtime +30 -delete",  target:"find /var/log -name '*.log' -type f",                     hint:'Navigate just after "-type f" then Ctrl+K cuts everything to the end.',    optimalKeys:5, category:'kill-end' },
  { id:108, collectionId:'kill-end', title:'Strip the pipeline',        description:"Remove '| grep error | wc -l' from the end.",              initial:'journalctl -u nginx -f | grep error | wc -l',             target:'journalctl -u nginx -f',                                  hint:'Navigate to just before "| grep"; Ctrl+K cuts to end.',                    optimalKeys:4, category:'kill-end' },
  { id:109, collectionId:'kill-end', title:'Remove trailing options',   description:"Remove '--no-pager --output=short-precise' from the end.", initial:'systemctl status nginx --no-pager --output=short-precise', target:'systemctl status nginx',                                  hint:'Navigate to just after "nginx"; Ctrl+K cuts everything to end.',           optimalKeys:4, category:'kill-end' },
  { id:110, collectionId:'kill-end', title:'Drop the debug suffix',     description:"Remove '--log-level=debug --verbose' from the end.",       initial:'helm install my-app ./chart --log-level=debug --verbose', target:'helm install my-app ./chart',                             hint:'Navigate to just before "--log-level"; Ctrl+K cuts to end.',               optimalKeys:4, category:'kill-end' },
  { id:215, collectionId:'kill-end', title:'Remove the output redirect',description:"Remove ' > /tmp/build.log' from the end.",                 initial:'npm run build > /tmp/build.log',                          target:'npm run build',                                           hint:'Navigate to just before ">"; Ctrl+K cuts the redirect.',                   optimalKeys:4, category:'kill-end' },
  { id:216, collectionId:'kill-end', title:'Trim the watch command',    description:"Remove '| grep -v Garbage' from the end of the tail.",     initial:'tail -f /var/log/app.log | grep -v Garbage',              target:'tail -f /var/log/app.log',                                hint:'Navigate to just before "| grep"; Ctrl+K cuts to end.',                    optimalKeys:4, category:'kill-end' },
  { id:217, collectionId:'kill-end', title:'Remove a tee output',       description:"Remove '| tee /tmp/out.txt' from the end.",                initial:'make test 2>&1 | tee /tmp/out.txt',                       target:'make test 2>&1',                                          hint:'Navigate to just before "| tee"; Ctrl+K cuts the rest.',                   optimalKeys:4, category:'kill-end' },
];

// ── Collection 6: Cut to Start (Ctrl+U) ───────────────────────────────────────
const killStartChallenges = [
  { id:3,   collectionId:'kill-start', title:'Strip the env prefix',   description:'Remove the environment-variable prefix before the command.', initial:'PYTHONPATH=/opt/lib DEBUG=1 python3 -m pytest tests/',   target:'python3 -m pytest tests/',                                hint:'Navigate to just before "python3" then Ctrl+U cuts back to start.',        optimalKeys:4, category:'kill-start' },
  { id:4,   collectionId:'kill-start', title:'Drop sudo',              description:'Remove "sudo " from the beginning of the command.',         initial:'sudo systemctl restart nginx',                            target:'systemctl restart nginx',                                 hint:'Alt+F jumps past "sudo"; Ctrl+U cuts everything before the cursor.',       optimalKeys:3, category:'kill-start' },
  { id:111, collectionId:'kill-start', title:'Remove the env vars',    description:"Remove 'NODE_ENV=production PORT=3000 ' from the start.",   initial:'NODE_ENV=production PORT=3000 node dist/server.js',       target:'node dist/server.js',                                     hint:'Alt+F x2 jumps past both env vars; Ctrl+U cuts them.',                    optimalKeys:4, category:'kill-start' },
  { id:112, collectionId:'kill-start', title:'Drop the path prefix',   description:"Remove '/usr/local/bin/' from in front of the command.",    initial:'/usr/local/bin/python3 -m venv .venv',                    target:'python3 -m venv .venv',                                   hint:'Alt+F jumps past the path token; Ctrl+U cuts it.',                         optimalKeys:3, category:'kill-start' },
  { id:218, collectionId:'kill-start', title:'Remove the watch prefix',description:"Remove 'watch -n1 ' from the beginning.",                   initial:'watch -n1 kubectl get pods',                              target:'kubectl get pods',                                        hint:'Alt+F x2 jumps past "watch" and "-n1"; Ctrl+U cuts them.',                 optimalKeys:4, category:'kill-start' },
  { id:219, collectionId:'kill-start', title:'Drop valgrind',          description:"Remove 'valgrind --leak-check=full ' from the start.",      initial:'valgrind --leak-check=full ./myprogram --config prod.toml', target:'./myprogram --config prod.toml',                          hint:'Alt+F x2 jumps past "valgrind" and "--leak-check=full"; Ctrl+U cuts them.',optimalKeys:4, category:'kill-start' },
  { id:220, collectionId:'kill-start', title:'Remove nice prefix',     description:"Remove 'nice -n 19 ' from the start.",                      initial:'nice -n 19 ffmpeg -i input.mp4 output.mp4',               target:'ffmpeg -i input.mp4 output.mp4',                          hint:'Alt+F x3 jumps past "nice", "-n", and "19"; Ctrl+U cuts them.',            optimalKeys:5, category:'kill-start' },
];

// ── Collection 7: Cut Word Backward (Ctrl+W) ──────────────────────────────────
// In Electron, Ctrl+W is fully supported.
// In a browser, use Alt+Backspace (identical readline binding).
const killWordBackChallenges = [
  { id:5,   collectionId:'kill-word-back', title:'Remove --force',              description:'Remove the dangerous --force flag from the git push.',   initial:'git push origin main --force',                            target:'git push origin main',                                    hint:'Ctrl+W at end of line removes "--force" in one stroke. (In a browser, use Alt+Backspace.)', optimalKeys:1, category:'kill-word-back' },
  { id:6,   collectionId:'kill-word-back', title:'Wrong branch',               description:'Remove the last argument (wrong branch name).',            initial:'git checkout -b feature/login wrong-base',                target:'git checkout -b feature/login',                           hint:'Ctrl+W x2: first removes "wrong-base", second removes the preceding space.', optimalKeys:2, category:'kill-word-back' },
  { id:24,  collectionId:'kill-word-back', title:'Remove the temp directory flag',description:"Remove ' -C /tmp' at the end of the tar command.",      initial:'tar -xzvf release.tar.gz -C /tmp',                        target:'tar -xzvf release.tar.gz',                                hint:'Ctrl+W x3 removes "/tmp", "-C", and the trailing space.',                  optimalKeys:3, category:'kill-word-back' },
  { id:28,  collectionId:'kill-word-back', title:'Remove pipe to less',        description:"Remove '| less' from the end of the command.",             initial:'journalctl -u nginx --since today | less',                target:'journalctl -u nginx --since today',                        hint:'Ctrl+W x2 removes "less" and then "|" together.',                          optimalKeys:2, category:'kill-word-back' },
  { id:2,   collectionId:'kill-word-back', title:'Drop the dry-run flag',      description:'Remove " --dry-run" at the end.',                          initial:'rsync -avz --progress /src/ user@host:/dst/ --dry-run',   target:'rsync -avz --progress /src/ user@host:/dst/',             hint:'Ctrl+W x2 removes "--dry-run" and the preceding space.',                   optimalKeys:2, category:'kill-word-back' },
  { id:221, collectionId:'kill-word-back', title:'Remove the no-cache flag',   description:"Remove '--no-cache' from the docker build.",               initial:'docker build -t myapp:latest . --no-cache',               target:'docker build -t myapp:latest .',                          hint:'Ctrl+W x2 removes "--no-cache" and the space before it.',                  optimalKeys:2, category:'kill-word-back' },
  { id:222, collectionId:'kill-word-back', title:'Strip the last pipe stage',  description:"Remove '| sort -u' from the end.",                         initial:'cut -d: -f1 /etc/passwd | sort -u',                       target:'cut -d: -f1 /etc/passwd',                                 hint:'Ctrl+W x3 removes "-u", "sort", and "|".',                                 optimalKeys:3, category:'kill-word-back' },
  { id:223, collectionId:'kill-word-back', title:'Remove verbose flag',        description:"Remove '--verbose' from the pytest command.",              initial:'pytest tests/ --verbose --tb=short',                      target:'pytest tests/ --tb=short',                                hint:'Navigate just after "--verbose"; Ctrl+W removes it and its space.',         optimalKeys:4, category:'kill-word-back' },
];

// ── Collection 8: Cut Word Forward (Alt+D) ────────────────────────────────────
const killWordFwdChallenges = [
  { id:7,   collectionId:'kill-word-fwd', title:'Delete a middle argument', description:'Remove "ubuntu:latest" from the docker command.',          initial:'docker run -it --rm ubuntu:latest bash',                  target:'docker run -it --rm bash',                                hint:'Navigate before "ubuntu:latest" then Alt+D removes the word forward.',      optimalKeys:5, category:'kill-word-fwd' },
  { id:113, collectionId:'kill-word-fwd', title:'Remove the --all flag',    description:"Remove '--all' from the git fetch command.",               initial:'git fetch --all --prune',                                 target:'git fetch --prune',                                       hint:'Navigate just before "--all"; Alt+D removes it.',                          optimalKeys:5, category:'kill-word-fwd' },
  { id:114, collectionId:'kill-word-fwd', title:'Drop the debug flag',      description:"Remove '--debug' from the webpack build.",                 initial:'webpack --config webpack.config.js --debug --progress',   target:'webpack --config webpack.config.js --progress',           hint:'Navigate just before "--debug"; Alt+D removes it.',                        optimalKeys:5, category:'kill-word-fwd' },
  { id:115, collectionId:'kill-word-fwd', title:'Remove the output file',   description:"Remove 'output.txt' from the middle of the tee command.",  initial:"tee output.txt | awk '{print $1}'",                       target:"tee | awk '{print $1}'",                                  hint:'Ctrl+A + Alt+F puts cursor after "tee"; Alt+D removes "output.txt".',      optimalKeys:4, category:'kill-word-fwd' },
  { id:224, collectionId:'kill-word-fwd', title:'Remove the volume mount',  description:"Remove '-v /data:/data' from the docker run.",             initial:'docker run --rm -v /data:/data -p 8080:8080 myapp',       target:'docker run --rm -p 8080:8080 myapp',                      hint:'Navigate just before "-v"; Alt+D x3 removes "-v", "/data", and ":/data".', optimalKeys:7, category:'kill-word-fwd' },
  { id:225, collectionId:'kill-word-fwd', title:'Drop the tag argument',    description:"Remove 'v1.0.0' from the git tag command.",                initial:'git tag -a v1.0.0 -m "Release 1.0.0"',                   target:'git tag -a -m "Release 1.0.0"',                           hint:'Navigate to just before "v1.0.0"; Alt+D removes it.',                      optimalKeys:4, category:'kill-word-fwd' },
  { id:226, collectionId:'kill-word-fwd', title:'Remove the test file',     description:"Remove 'test_auth.py' from the pytest command.",           initial:'pytest -v test_auth.py test_api.py',                      target:'pytest -v test_api.py',                                   hint:'Navigate just before "test_auth.py"; Alt+D removes it.',                   optimalKeys:5, category:'kill-word-fwd' },
];

// ── Collection 9: Yank / Paste (Ctrl+Y) ───────────────────────────────────────
const yankChallenges = [
  { id:9,   collectionId:'yank', title:'Move the output file',        description:'Move "output.log" from after "tee" to the end.',              initial:'tee output.log | grep ERROR | sort',                      target:'tee | grep ERROR | sort output.log',                       hint:'Navigate after "tee "; Ctrl+W removes "output.log"; Ctrl+E; type " "; Ctrl+Y.', optimalKeys:9, category:'yank' },
  { id:116, collectionId:'yank', title:'Reorder a flag',              description:"Move '--debug' from the end to right after 'python3'.",        initial:'python3 app.py --debug',                                  target:'python3 --debug app.py',                                   hint:'Navigate to " --debug"; Ctrl+K removes it; Ctrl+A + Alt+F; Ctrl+Y.',       optimalKeys:8, category:'yank' },
  { id:117, collectionId:'yank', title:'Swap file arguments',         description:"Swap '/etc/hosts' and '/etc/resolv.conf' in the cat command.", initial:'cat /etc/hosts /etc/resolv.conf',                         target:'cat /etc/resolv.conf /etc/hosts',                          hint:'Navigate after "/etc/hosts"; Ctrl+K removes rest; Ctrl+A+Alt+F x2; Ctrl+Y.', optimalKeys:8, category:'yank' },
  { id:118, collectionId:'yank', title:'Duplicate a symlink target',  description:"Add 'python3' as the link name after the target path.",        initial:'ln -s /usr/local/bin/python3',                            target:'ln -s /usr/local/bin/python3 python3',                     hint:'Alt+B moves before "python3"; Ctrl+W removes it; Ctrl+E; type " "; Ctrl+Y.', optimalKeys:5, category:'yank' },
  { id:227, collectionId:'yank', title:'Reuse the path',              description:"Replace '/tmp' with the source directory '/var/log/app'.",     initial:'cp /var/log/app/error.log /tmp',                          target:'cp /var/log/app/error.log /var/log/app',                   hint:'Navigate before "/var/log/app"; Ctrl+K; navigate to end; Ctrl+Y.',          optimalKeys:8, category:'yank' },
  { id:228, collectionId:'yank', title:'Duplicate a remote host',     description:"Add a second rsync destination with the same host.",           initial:'rsync -av /data/ user@backup1:/data/',                    target:'rsync -av /data/ user@backup1:/data/ user@backup1:/mirror/', hint:'Navigate before "user@backup1"; Ctrl+W; Ctrl+E; type " "; Ctrl+Y; type ":/mirror/".', optimalKeys:14, category:'yank' },
  { id:229, collectionId:'yank', title:'Move a filter forward',       description:"Move 'grep -i error' from before 'sort' to after 'sort'.",     initial:'cat app.log | grep -i error | sort | uniq -c',            target:'cat app.log | sort | grep -i error | uniq -c',             hint:'Navigate before "grep"; Ctrl+K removes "grep -i error |"; after "sort |"; Ctrl+Y.', optimalKeys:10, category:'yank' },
];

// ── Collection 10: Transpose Characters (Ctrl+T) ──────────────────────────────
const transposeChallenges = [
  { id:10,  collectionId:'transpose', title:'Transposed letters',      description:"Fix the typo 'sattus' to 'status'.",                          initial:'git sattus',                                             target:'git status',                                              hint:"Position cursor between the swapped pair (after 'a', before 't') and press Ctrl+T.", optimalKeys:4, category:'transpose' },
  { id:11,  collectionId:'transpose', title:'Swapped characters',      description:"Fix 'mkdri' to 'mkdir'.",                                     initial:'mkdri -p /opt/app/logs',                                 target:'mkdir -p /opt/app/logs',                                  hint:'Ctrl+T swaps the character before the cursor with the one at the cursor.',  optimalKeys:3, category:'transpose' },
  { id:20,  collectionId:'transpose', title:'Bump the npm script',     description:"Change 'buidl' to 'build'.",                                  initial:'npm run buidl --prefix packages/frontend',               target:'npm run build --prefix packages/frontend',                hint:'Navigate to after "bui"; Ctrl+T swaps "id" to give "build".',              optimalKeys:4, category:'transpose' },
  { id:119, collectionId:'transpose', title:'Fix a two-character swap',description:"Fix 'pytohn' to 'python'.",                                   initial:'pytohn3 script.py',                                      target:'python3 script.py',                                       hint:'Navigate so the cursor sits after "to"; Ctrl+T swaps to give "ot".',       optimalKeys:3, category:'transpose' },
  { id:230, collectionId:'transpose', title:'Fix another transposition',description:"Fix 'dokcer' to 'docker'.",                                  initial:'dokcer ps -a',                                           target:'docker ps -a',                                            hint:'Position after "ok"; Ctrl+T swaps to give "ok" -> "ko".',                   optimalKeys:3, category:'transpose' },
  { id:231, collectionId:'transpose', title:'Repair the git verb',     description:"Fix 'comit' to 'commit'.",                                    initial:'git comit -m "fix: handle null case"',                   target:'git commit -m "fix: handle null case"',                   hint:'Navigate after "com"; type the missing "m".',                               optimalKeys:4, category:'transpose' },
];

// ── Collection 11: Mixed Techniques ──────────────────────────────────────────
const miscChallenges = [
  { id:232, collectionId:'misc', title:'Fix a wrong flag order',       description:"Move '-f' so it comes before 'myfile.txt'.",                   initial:'gcc myfile.txt -f -o app',                               target:'gcc -f myfile.txt -o app',                                hint:'Navigate to "-f"; Ctrl+W removes it; navigate before "myfile.txt"; Ctrl+Y.', optimalKeys:8, category:'misc' },
  { id:233, collectionId:'misc', title:'Insert a missing pipe',        description:"Add '| head -20' at the end of the command.",                 initial:'dmesg',                                                  target:'dmesg | head -20',                                        hint:'Ctrl+E to go to end, type "| head -20".',                                   optimalKeys:11, category:'misc' },
  { id:234, collectionId:'misc', title:'Change the port',              description:"Change port 3000 to 8080 in the node command.",               initial:'node server.js --port 3000 --host 0.0.0.0',              target:'node server.js --port 8080 --host 0.0.0.0',               hint:'Alt+B x3 from end lands on "3000"; delete 4 chars, type "8080".',           optimalKeys:8, category:'misc' },
  { id:235, collectionId:'misc', title:'Swap two arguments',           description:"Swap 'src' and 'dst' in the mv command.",                      initial:'mv dst src',                                             target:'mv src dst',                                              hint:'Navigate to "dst"; Ctrl+W removes it; Ctrl+E; type " "; Ctrl+Y.',           optimalKeys:7, category:'misc' },
  { id:236, collectionId:'misc', title:'Add a missing option',         description:"Add '-R' to make the chmod recursive.",                       initial:'chmod 755 /var/www/html',                                target:'chmod -R 755 /var/www/html',                               hint:'Ctrl+A + Alt+F puts cursor after "chmod"; type " -R".',                     optimalKeys:5, category:'misc' },
  { id:237, collectionId:'misc', title:'Fix a wrong target',           description:"Change '/var/log' to '/var/log/nginx' in the tail command.",   initial:'tail -f /var/log',                                       target:'tail -f /var/log/nginx',                                  hint:'Ctrl+E to go to end; type "/nginx".',                                       optimalKeys:7, category:'misc' },
];

// ── Collection 12: Graduate (all shortcuts combined) ──────────────────────────
const graduateChallenges = [
  { id:21,  collectionId:'graduate', title:'Switch git remote',          description:"Change 'upstream' to 'origin' in the push command.",          initial:'git push upstream feature/dark-mode',                     target:'git push origin feature/dark-mode',                       hint:'Alt+B x2 before "upstream"; Ctrl+W to remove it; type "origin".',            optimalKeys:9,  category:'graduate' },
  { id:22,  collectionId:'graduate', title:'Replace the AWS profile',    description:"Change 'staging' to 'production' in the AWS profile.",        initial:'aws --profile staging s3 ls s3://my-company-data',        target:'aws --profile production s3 ls s3://my-company-data',     hint:'Alt+B x3 to "staging"; Ctrl+W removes it; type "production".',               optimalKeys:12, category:'graduate' },
  { id:14,  collectionId:'graduate', title:'Fix the port',               description:"Change port 8080 to 9090 in the ssh tunnel.",                  initial:'ssh -L 8080:localhost:8080 user@192.168.1.10',            target:'ssh -L 9090:localhost:9090 user@192.168.1.10',             hint:'Alt+B navigates to each number block; Backspace + retype.',                   optimalKeys:10, category:'graduate' },
  { id:26,  collectionId:'graduate', title:'Change the user',            description:"Replace 'alice' with 'bob' everywhere in the scp path.",       initial:'scp -r alice@server:/home/alice/data /local/backup',      target:'scp -r bob@server:/home/bob/data /local/backup',           hint:'Alt+F/B to navigate to each "alice"; Ctrl+W + retype "bob".',                 optimalKeys:14, category:'graduate' },
  { id:120, collectionId:'graduate', title:'Clean up the rsync',         description:"Remove '--delete' and rename user 'alice' to 'bob'.",          initial:'rsync -avz --delete /home/alice/src/ server:/backup/',    target:'rsync -avz /home/bob/src/ server:/backup/',                hint:'Ctrl+A+Alt+F x2+Alt+D removes "--delete"; Alt+F x2; Ctrl+W + type "bob".',    optimalKeys:14, category:'graduate' },
  { id:238, collectionId:'graduate', title:'Rebuild from scratch',       description:"Add '--no-cache' and change 'myapp:dev' to 'myapp:prod'.",     initial:'docker build -t myapp:dev .',                            target:'docker build --no-cache -t myapp:prod .',                  hint:'Navigate after "build"; type " --no-cache"; Alt+B x2 to "dev"; Ctrl+W + type "prod".', optimalKeys:17, category:'graduate' },
  { id:239, collectionId:'graduate', title:'Convert to background job',  description:"Add 'nohup', remove '--foreground', and append '&'.",          initial:'gunicorn app:app --foreground --workers 4',               target:'nohup gunicorn app:app --workers 4 &',                     hint:'Ctrl+A to prepend "nohup "; navigate to "--foreground"; Ctrl+W x2; Ctrl+E; type " &".', optimalKeys:16, category:'graduate' },
  { id:240, collectionId:'graduate', title:'Fix a multi-part mistake',   description:"Fix 'grpe' and change 'DEBUG' to 'ERROR'.",                    initial:"grpe -r DEBUG /var/log",                                 target:"grep -r ERROR /var/log",                                  hint:'Ctrl+A; fix "grpe" with Ctrl+D x2+type; Alt+F x2; Ctrl+W + type "ERROR".',   optimalKeys:11, category:'graduate' },
  { id:241, collectionId:'graduate', title:'Build and push',             description:"Add ':latest' tag and a push command after '&&'.",             initial:'docker build -t myrepo/app .',                           target:'docker build -t myrepo/app:latest . && docker push myrepo/app:latest', hint:'Navigate after "myrepo/app"; type ":latest"; Ctrl+E; type " && docker push myrepo/app:latest".', optimalKeys:42, category:'graduate' },
  { id:242, collectionId:'graduate', title:'Swap environment and region',description:"Change 'dev' to 'prod' and 'us-west-2' to 'eu-central-1'.",   initial:'aws eks update-kubeconfig --name dev-cluster --region us-west-2', target:'aws eks update-kubeconfig --name prod-cluster --region eu-central-1', hint:'Alt+B x2 to "dev"; Ctrl+W + type "prod"; Alt+B to "us"; delete + type "eu-central".', optimalKeys:20, category:'graduate' },
];

export const COLLECTIONS = [
  { id:'line-nav',       name:'Line Navigation',      shortcut:'Ctrl+A / Ctrl+E',    description:'Jump instantly to the start or end of the line.',                                          challenges:lineNavChallenges },
  { id:'word-nav',       name:'Word Navigation',      shortcut:'Alt+F / Alt+B',      description:'Leap forward or backward one whole word at a time.',                                        challenges:wordNavChallenges },
  { id:'char-nav',       name:'Character Navigation', shortcut:'Ctrl+F / Ctrl+B',    description:'Step precisely one character at a time.',                                                   challenges:charNavChallenges },
  { id:'char-del',       name:'Character Deletion',   shortcut:'Ctrl+D / Backspace', description:'Delete a single character, forward or backward.',                                           challenges:charDelChallenges },
  { id:'kill-end',       name:'Cut to End',           shortcut:'Ctrl+K',             description:'Slice everything from the cursor to the end of the line.',                                  challenges:killEndChallenges },
  { id:'kill-start',     name:'Cut to Start',         shortcut:'Ctrl+U',             description:'Erase everything from the cursor back to the beginning.',                                   challenges:killStartChallenges },
  { id:'kill-word-back', name:'Cut Word Backward',    shortcut:'Ctrl+W',             description:'Delete the whole word immediately before the cursor.',                                      challenges:killWordBackChallenges },
  { id:'kill-word-fwd',  name:'Cut Word Forward',     shortcut:'Alt+D',              description:'Delete the whole word immediately after the cursor.',                                       challenges:killWordFwdChallenges },
  { id:'yank',           name:'Yank (Paste)',          shortcut:'Ctrl+Y',             description:'Paste back text that was previously cut.',                                                  challenges:yankChallenges },
  { id:'transpose',      name:'Transpose Characters', shortcut:'Ctrl+T',             description:'Swap the two characters around the cursor to fix transposition typos.',                    challenges:transposeChallenges },
  { id:'misc',           name:'Mixed Techniques',     shortcut:'All shortcuts',      description:'Challenges combining navigation, deletion, and cut/yank techniques.',                      challenges:miscChallenges },
  { id:'graduate',       name:'Graduate',             shortcut:'All shortcuts',      description:"Complex, real-world challenges combining everything you have learnt. You've got this!",    challenges:graduateChallenges },
];

/** All challenges as a flat list, in collection order. */
export const CHALLENGES = COLLECTIONS.flatMap(c => c.challenges);

/**
 * Return `count` challenges drawn randomly (without replacement) from CHALLENGES.
 * @param {number} count
 * @param {function} [rng]  Optional RNG; defaults to Math.random.
 */
export function selectChallenges(count, rng = Math.random) {
  const shuffled = [...CHALLENGES].sort(() => rng() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}
